name: workbook
channels:
        - conda-forge
        - bioconda
dependencies:

        # core
        - jupyterlab_widgets
        - ipywidgets
        - ipykernel 
        - jupyterlab

        # computational
        - python=3.9
        - pandas
        - numpy
        - scikit-learn

        # Visualisation
        - matplotlib


#conda install -c conda-forge ipympl ## for jupyter

