name: mlz
channels:
        - conda-forge
        - bioconda
dependencies:
        - matplotlib
        - pandas
        - jupyterlab_widgets
        - ipywidgets
        - ipykernel 
        - jupyterlab
        - numpy
        - scipy
        - python=3.9
        - scikit-learn

#conda install -c conda-forge ipympl ## for jupyter

